export interface BusStop {
  stopId?: number,
  stopCode?: string,
  stopName?: string,
  stopShortName?: string,
  stopDesc?: string,
  subName?: string,
  date?: Date,
  zoneId?: number,
  zoneName?: string,
  virtual?: boolean,
  nonpassenger?: boolean,
  depot?: boolean,
  ticketZoneBorder?: boolean,
  onDemand?: boolean,
  activationDate?: Date,
  stopLat?: number,
  stopLon?: number,
  stopUrl?: string,
  locationType?: string,
  parentStation?: number | string,
  stopTimezone?: string,
  wheelchairBoarding?: boolean
}